env:
  DB_USERNAME_TEST: postgres
  DB_PASSWORD_TEST: postgres
  RUBY_VERSION: 3.0.1

name: Tests
on: [push]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: ${{ env.DB_USERNAME_TEST }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD_TEST }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Run rubocop
        run: bundler exec rubocop
      - name: Create database
        run: |
          cp config/database.yml{.example,}
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rspec
